CREATE TABLE IF NOT EXISTS articles(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text,
    url text NOT NULL CHECK (name <> ''),
    content text,
    header text,
    subheader text,
    publishdate date NOT NULL,
    author text
);